
var P={
"90051400123":{vn:"VN-00012847",id:"90051400123",name:"Anna Amutenya",dob:"14 May 1990",sex:"Female",nationality:"Namibian",phone:"+264 81 555 0142",town:"Windhoek",coverage:"State patient",allergies:["Penicillin — severe reaction"],conditions:["Hypertension","Migraine"],meds:["Amlodipine 5 mg once daily"],history:[["03 Aug 2026","Oshakati Intermediate Hospital","Persistent headaches","Migraine"],["17 Mar 2026","Katutura Intermediate Hospital","Abdominal pain","Resolved"]],labs:["Full Blood Count — completed 11 Aug 2026","Kidney Function — completed 11 Aug 2026"]},
"P99887766":{vn:"VN-00048293",id:"P99887766",name:"Tendai Moyo",dob:"02 February 1988",sex:"Male",nationality:"Zimbabwean",phone:"+264 81 330 1010",town:"Windhoek",coverage:"Private medical aid",allergies:["No known drug allergies"],conditions:["Asthma"],meds:["Salbutamol inhaler as needed"],history:[["29 Jul 2026","Windhoek Central Hospital","Asthma exacerbation","Asthma"]],labs:[]},
"BR-2022-00088":{vn:"VN-00035821",id:"BR-2022-00088",name:"Tulela Amutenya",dob:"06 February 2022",sex:"Male",nationality:"Namibian",phone:"Guardian contact",town:"Windhoek",coverage:"Dependent / state patient",allergies:["No known allergies"],conditions:[],meds:[],history:[["01 Jul 2026","Windhoek Central Hospital","Routine review","Well child"]],labs:[]}
};
var roles={receptionist:{label:"Receptionist"},nurse:{label:"Nurse"},doctor:{label:"Doctor"},billing:{label:"Billing Officer"}};
var S={user:null,page:"dashboard",patient:null,audit:[]};
function loadQueue(){try{return JSON.parse(localStorage.getItem("verinam_queue_v4")||"[]")}catch(e){return[]}}
function saveQueue(q){localStorage.setItem("verinam_queue_v4",JSON.stringify(q))}
function E(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function role(){return roles[S.user.role]}function log(x){S.audit.unshift([new Date().toLocaleString(),S.user.name,role().label,x])}
function render(){document.getElementById("app").innerHTML=S.user?shell():login()}
function login(){return '<div class="login"><div class="login-card"><div class="brand"><div class="logo">V</div><div><b>VeriNam</b><div class="muted">Healthcare prototype v4</div></div></div><h1>Secure access</h1>'+fld("ln","Name","Demo User")+'<div class="field"><label>Role</label><select id="lr"><option value="receptionist">Receptionist</option><option value="nurse">Nurse</option><option value="doctor">Doctor</option><option value="billing">Billing Officer</option></select></div><div class="field"><label>Facility</label><select id="lf"><option>Windhoek Central Hospital</option><option>Oshakati Intermediate Hospital</option><option>Walvis Bay State Hospital</option></select></div><button class="primary" style="width:100%" onclick="signin()">Sign in</button></div></div>'}
function fld(id,l,v){return '<div class="field"><label>'+E(l)+'</label><input id="'+id+'" value="'+E(v||"")+'"></div>'}
function signin(){S.user={name:document.getElementById("ln").value||"Demo User",role:document.getElementById("lr").value,facility:document.getElementById("lf").value};log("Signed in");S.page=S.user.role==="doctor"?"queue":"dashboard";render()}
function shell(){return '<div class="shell">'+side()+'<section class="content"><header class="top"><div><b>VeriNam</b><div class="muted" style="font-size:12px">Patient flow & clinical access</div></div><div class="meta">'+E(S.user.name)+'<br>'+E(role().label)+' · '+E(S.user.facility)+'</div></header><main class="main">'+page()+'</main></section></div>'}
function side(){return '<aside class="sidebar"><div class="brand"><div class="logo">V</div><b>VeriNam</b></div><div class="nav">'+nav("dashboard","Dashboard")+nav("find","Scan / Find Patient")+nav("queue","Today's Patient Queue")+nav("audit","Audit Log")+'<button onclick="logout()">Sign out</button></div></aside>'}
function nav(p,t){return '<button class="'+(S.page===p?"active":"")+'" onclick="go(\''+p+'\')">'+t+'</button>'}function go(p){S.page=p;render()}function logout(){S={user:null,page:"dashboard",patient:null,audit:S.audit};render()}
function page(){if(S.page==="find")return find();if(S.page==="queue")return queue();if(S.page==="patient")return patient();if(S.page==="clinical")return clinical();if(S.page==="audit")return audit();return dash()}
function dash(){var q=facilityQueue();return '<h1 class="title">Healthcare Dashboard</h1><p class="subtitle">Today at '+E(S.user.facility)+'</p><div class="grid g4">'+kpi("Waiting today",q.filter(function(x){return x.status!=="Completed"}).length)+kpi("Checked in",q.filter(function(x){return x.status==="Checked In"}).length)+kpi("With doctor",q.filter(function(x){return x.status==="With Doctor"}).length)+kpi("Completed",q.filter(function(x){return x.status==="Completed"}).length)+'</div><div class="grid g2" style="margin-top:17px"><div class="card"><h3>Patient arrival</h3><div class="search"><input id="dq" placeholder="ID / passport / birth record"><button class="primary" onclick="lookup(\'dq\')">Find patient</button></div><p class="muted">Demo: 90051400123 · P99887766 · BR-2022-00088</p></div><div class="card"><h3>Today's workflow</h3><p><b>Checked In → Triage → Ready for Doctor → With Doctor → Completed</b></p><p class="muted">The queue persists on this device when you sign out and change roles.</p><button class="secondary" onclick="go(\'queue\')">Open patient queue</button></div></div>'}
function kpi(a,b){return '<div class="card"><div class="muted">'+E(a)+'</div><div class="kpi">'+E(b)+'</div></div>'}
function find(){return '<h1 class="title">Scan / Find Patient</h1><p class="subtitle">Identify a patient and start today's visit.</p><div class="card"><div class="search"><input id="fq" placeholder="ID / passport / birth record"><button class="primary" onclick="lookup(\'fq\')">Scan / Search</button></div></div>'}
function lookup(id){var q=document.getElementById(id).value.trim(),p=P[q];if(!p){alert("No matching demo patient.");return}S.patient=p;log("Identified "+p.vn);S.page="patient";render()}
function patient(){var p=S.patient,q=findEncounter(p.vn),s='<div class="patient-head"><div><h1 class="title">'+E(p.name)+'</h1><p class="subtitle">'+E(p.vn)+' · '+E(p.id)+' · '+E(p.dob)+' · '+E(p.nationality)+'</p></div><span class="badge ok">Identity verified</span></div><div class="grid g2"><div class="card"><h3>Patient details</h3>'+info("Phone",p.phone)+info("Town",p.town)+info("Funding",p.coverage)+'</div><div class="card"><h3>Today's visit</h3>';
if(q)s+='<div class="success">This patient is already in today’s queue: <b>'+E(q.status)+'</b>.</div><div class="actions" style="margin-top:12px"><button class="secondary" onclick="go(\'queue\')">Open queue</button>'+(S.user.role==="doctor"&&q.status==="Ready for Doctor"?'<button class="primary" onclick="startDoctor(\''+E(q.id)+'\')">Open Clinical View</button>':'')+'</div>';
else if(S.user.role==="receptionist"||S.user.role==="nurse")s+='<p class="muted">Create a visit so the next care team can see the patient in their queue.</p><div class="field"><label>Visit reason</label><input id="reason" value="General consultation"></div><button class="primary" onclick="checkin()">Check in patient</button>';
else s+='<div class="restricted">No active visit for this patient today. Reception or nursing must check the patient in first.</div>';
return s+'</div></div>'}
function info(a,b){return '<div class="row"><div><div class="label">'+E(a)+'</div><div class="value">'+E(b)+'</div></div></div>'}
function checkin(){var q=loadQueue(),now=Date.now(),e={id:"ENC-"+now,vn:S.patient.vn,patientId:S.patient.id,name:S.patient.name,facility:S.user.facility,status:"Checked In",reason:document.getElementById("reason").value||"General consultation",created:new Date().toLocaleString()};q.push(e);saveQueue(q);log("Checked in "+S.patient.vn);S.page="queue";render()}
function facilityQueue(){return loadQueue().filter(function(x){return x.facility===S.user.facility})}
function findEncounter(vn){var q=facilityQueue();for(var i=q.length-1;i>=0;i--)if(q[i].vn===vn&&q[i].status!=="Completed")return q[i];return null}
function queue(){var q=facilityQueue(),s='<h1 class="title">Today’s Patient Queue</h1><p class="subtitle">'+E(S.user.facility)+' · shared workflow on this device</p>';if(!q.length)return s+'<div class="card"><div class="muted">No patients checked in yet.</div></div>';for(var i=0;i<q.length;i++){var e=q[i];s+='<div class="queue-card"><div class="queue-top"><div><div class="value">'+E(e.name)+'</div><div class="label">'+E(e.vn)+' · '+E(e.reason)+' · '+E(e.created)+'</div></div><span class="badge '+(e.status==="Completed"?"ok":e.status==="With Doctor"?"warn":"info")+'">'+E(e.status)+'</span></div>'+steps(e.status)+'<div class="actions" style="margin-top:12px">'+queueActions(e)+'</div></div>'}return s}
function steps(st){var a=["Checked In","Triage","Ready for Doctor","With Doctor","Completed"],idx=a.indexOf(st),s='<div class="steps">';for(var i=0;i<a.length;i++)s+='<span class="step '+(i<idx?"done":i===idx?"current":"")+'">'+E(a[i])+'</span>';return s+'</div>'}
function queueActions(e){if(e.status==="Completed")return "";if(S.user.role==="nurse"){if(e.status==="Checked In")return '<button class="primary" onclick="setStatus(\''+e.id+'\',\'Triage\')">Start triage</button>';if(e.status==="Triage")return '<button class="primary" onclick="setStatus(\''+e.id+'\',\'Ready for Doctor\')">Send to doctor</button>'}if(S.user.role==="doctor"&&e.status==="Ready for Doctor")return '<button class="primary" onclick="startDoctor(\''+e.id+'\')">Open Clinical View</button>';if(S.user.role==="doctor"&&e.status==="With Doctor")return '<button class="primary" onclick="startDoctor(\''+e.id+'\')">Continue Clinical View</button>';return '<span class="muted">Waiting for next workflow step.</span>'}
function setStatus(id,st){var q=loadQueue();for(var i=0;i<q.length;i++)if(q[i].id===id){q[i].status=st;log(q[i].vn+" → "+st)}saveQueue(q);render()}
function startDoctor(id){var q=loadQueue(),e=null;for(var i=0;i<q.length;i++)if(q[i].id===id){e=q[i];q[i].status="With Doctor"}if(!e)return;saveQueue(q);S.patient=P[e.patientId];S.encounterId=id;log("Doctor opened clinical view for "+e.vn);S.page="clinical";render()}
function clinical(){var p=S.patient,e=getEnc(S.encounterId);if(!p||!e)return '<div class="restricted">No active clinical encounter.</div>';return '<div class="clinical-header"><div class="muted">CLINICAL VIEW · ACTIVE ENCOUNTER</div><h1 style="margin:5px 0">'+E(p.name)+'</h1><div>'+E(p.vn)+' · '+E(e.reason)+' · '+E(S.user.facility)+'</div></div><div class="grid g3"><div class="card"><h3>Safety summary</h3>'+info("Allergies",p.allergies.join(", ")||"None recorded")+info("Conditions",p.conditions.join(", ")||"None recorded")+info("Medication",p.meds.join(", ")||"None recorded")+'</div><div class="card"><h3>Recent labs</h3>'+list(p.labs)+'</div><div class="card"><h3>Visit notes</h3><div class="field"><label>Clinical note</label><textarea id="note" rows="6" placeholder="Enter consultation note..."></textarea></div></div></div><div class="card" style="margin-top:17px"><h3>Previous encounters</h3><div class="tablewrap"><table><tr><th>Date</th><th>Facility</th><th>Reason</th><th>Diagnosis</th></tr>'+hist(p)+'</table></div><div class="actions" style="margin-top:14px"><button class="secondary" onclick="go(\'queue\')">Back to queue</button><button class="primary" onclick="complete()">Complete encounter</button></div></div>'}
function list(a){if(!a.length)return '<div class="muted">No recent results.</div>';var s="";for(var i=0;i<a.length;i++)s+='<div class="row"><div>'+E(a[i])+'</div></div>';return s}
function hist(p){var s="";for(var i=0;i<p.history.length;i++)s+='<tr><td>'+E(p.history[i][0])+'</td><td>'+E(p.history[i][1])+'</td><td>'+E(p.history[i][2])+'</td><td>'+E(p.history[i][3])+'</td></tr>';return s}
function getEnc(id){var q=loadQueue();for(var i=0;i<q.length;i++)if(q[i].id===id)return q[i];return null}
function complete(){var q=loadQueue();for(var i=0;i<q.length;i++)if(q[i].id===S.encounterId){q[i].status="Completed";q[i].completed=new Date().toLocaleString();q[i].note=document.getElementById("note").value||"";log("Completed encounter for "+q[i].vn)}saveQueue(q);S.page="queue";render()}
function audit(){var s='<h1 class="title">Session Audit Log</h1><div class="card"><div class="tablewrap"><table><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th></tr>';for(var i=0;i<S.audit.length;i++)s+='<tr><td>'+E(S.audit[i][0])+'</td><td>'+E(S.audit[i][1])+'</td><td>'+E(S.audit[i][2])+'</td><td>'+E(S.audit[i][3])+'</td></tr>';return s+'</table></div></div>'}
render();
