
var patients={
"90051400123":{vn:"VN-00012847",id:"90051400123",idtype:"Namibian ID",name:"Anna Amutenya",dob:"14 May 1990",sex:"Female",nationality:"Namibian",status:"Authoritatively verified",phone:"+264 81 555 0142",town:"Windhoek",emergency:"Petrus Amutenya · +264 81 777 8211",coverage:{type:"State patient",provider:"Public healthcare",status:"Active"},allergies:["Penicillin — severe reaction"],conditions:["Hypertension","Migraine"],meds:["Amlodipine 5 mg once daily"],encounters:[["03 Aug 2026","Oshakati Intermediate Hospital","Outpatient","Persistent headaches","Migraine"],["17 Mar 2026","Katutura Intermediate Hospital","Emergency","Abdominal pain","Resolved"]],labs:[["11 Aug 2026","Full Blood Count","Oshakati Laboratory","Completed"],["11 Aug 2026","Kidney Function","Oshakati Laboratory","Completed"]],referrals:[["12 Aug 2026","Oshakati Intermediate Hospital","Windhoek Cardiology","Cardiology assessment","Active"]],children:["BR-2022-00088"]},
"P99887766":{vn:"VN-00048293",id:"P99887766",idtype:"Passport",name:"Tendai Moyo",dob:"02 February 1988",sex:"Male",nationality:"Zimbabwean",status:"Document verified",phone:"+264 81 330 1010",town:"Windhoek",emergency:"Rudo Moyo · +264 81 220 4030",coverage:{type:"Private medical aid",provider:"Example Health Fund",status:"Active"},allergies:["No known drug allergies"],conditions:["Asthma"],meds:["Salbutamol inhaler as needed"],encounters:[["29 Jul 2026","Windhoek Central Hospital","Emergency","Asthma exacerbation","Asthma"]],labs:[],referrals:[],children:[]},
"BR-2022-00088":{vn:"VN-00035821",id:"BR-2022-00088",idtype:"Birth record",name:"Tulela Amutenya",dob:"06 February 2022",sex:"Male",nationality:"Namibian",status:"Birth record verified",phone:"Guardian contact",town:"Windhoek",emergency:"Anna Amutenya · Parent",coverage:{type:"Dependent / state patient",provider:"Public healthcare",status:"Active"},allergies:["No known allergies"],conditions:[],meds:[],encounters:[["01 Jul 2026","Windhoek Central Hospital","Paediatrics","Routine review","Well child"]],labs:[],referrals:[],children:[],guardian:{name:"Anna Amutenya",vn:"VN-00012847",relationship:"Parent"}}
};
var roles={receptionist:{label:"Receptionist",clinical:false,coverage:true,checkin:true,register:true},nurse:{label:"Nurse",clinical:true,coverage:false,checkin:true,register:false},doctor:{label:"Doctor",clinical:true,coverage:false,checkin:false,register:false},billing:{label:"Billing Officer",clinical:false,coverage:true,checkin:false,register:false},admin:{label:"System Administrator",clinical:false,coverage:false,checkin:false,register:false}};
var S={user:null,page:"dashboard",patient:null,encounter:false,tab:"summary",audit:[],emergency:false,unknown:""};
function E(x){return String(x==null?"":x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function R(){return roles[S.user.role]}function A(action,result){S.audit.unshift([new Date().toLocaleString(),S.user?S.user.name:"System",S.user?R().label:"System",S.user?S.user.facility:"",action,result||"GRANTED"])}
function render(){document.getElementById("app").innerHTML=S.user?shell():login()}
function login(){return '<div class="login"><div class="login-card"><div class="brand"><div class="logo">V</div><div><strong>VeriNam</strong><div class="muted">Healthcare prototype v3</div></div></div><h1>Secure access</h1><p class="muted">Use a fictional role to explore the national health workflow.</p>'+fld("ln","Name","Demo User")+'<div class="field"><label>Role</label><select id="lr"><option value="receptionist">Receptionist</option><option value="nurse">Nurse</option><option value="doctor">Doctor</option><option value="billing">Billing Officer</option><option value="admin">System Administrator</option></select></div><div class="field"><label>Facility</label><select id="lf"><option>Windhoek Central Hospital</option><option>Oshakati Intermediate Hospital</option><option>Walvis Bay State Hospital</option></select></div><button class="primary" style="width:100%" onclick="signin()">Sign in</button></div></div>'}
function signin(){S.user={name:document.getElementById("ln").value||"Demo User",role:document.getElementById("lr").value,facility:document.getElementById("lf").value};A("Signed in");render()}
function shell(){return '<div class="shell">'+side()+'<section class="content"><header class="top"><div><b>VeriNam</b><div class="muted" style="font-size:12px">One identity · authorised services · less paperwork</div></div><div class="meta">'+E(S.user.name)+'<br>'+E(R().label)+' · '+E(S.user.facility)+'</div></header><main class="main">'+page()+'</main></section></div>'}
function side(){return '<aside class="sidebar"><div class="brand"><div class="logo">V</div><strong>VeriNam</strong></div><div class="nav">'+nav("dashboard","Dashboard")+nav("find","Scan / Find Patient")+nav("register","First-time Registration")+nav("emergency","Emergency Access")+nav("audit","Audit Log")+'<button onclick="logout()">Sign out</button></div></aside>'}
function nav(p,t){return '<button class="'+(S.page===p?"active":"")+'" onclick="go(\''+p+'\')">'+t+'</button>'}function go(p){S.page=p;render()}function logout(){S={user:null,page:"dashboard",patient:null,encounter:false,tab:"summary",audit:[],emergency:false,unknown:""};render()}
function page(){if(S.page==="find")return find();if(S.page==="register")return register();if(S.page==="patient")return patient();if(S.page==="emergency")return emergency();if(S.page==="audit")return audit();return dash()}
function dash(){return '<h1 class="title">Healthcare Dashboard</h1><p class="subtitle">Identify patients quickly while keeping access purpose-based and auditable.</p><div class="grid g4">'+kpi("Role",R().label)+kpi("Facility",S.user.facility)+kpi("Exchange","Connected")+kpi("Privacy","Role + encounter")+'</div><div class="grid g2" style="margin-top:17px"><div class="scan"><h3>Patient arrival</h3><p class="muted">Scan or enter a Namibian ID, passport, birth record or VeriNam ID.</p><div class="search"><input id="q1" placeholder="e.g. 90051400123"><button class="primary" onclick="lookup(\'q1\')">Find patient</button></div><p class="muted" style="font-size:12px">Demo: 90051400123 · P99887766 · BR-2022-00088</p></div><div class="card"><h3>Quick workflows</h3><div class="actions"><button class="secondary" onclick="go(\'register\')">First-time patient</button><button class="emergency" onclick="go(\'emergency\')">Emergency / unidentified</button></div><p class="muted">The goal is to avoid repeating long registration forms when trusted information already exists.</p></div></div>'}
function kpi(a,b){return '<div class="card"><div class="muted">'+E(a)+'</div><div class="kpi">'+E(b)+'</div></div>'}
function find(){return '<h1 class="title">Scan / Find Patient</h1><p class="subtitle">Identity lookup does not itself grant access to health information.</p><div class="scan"><div class="scanbox"><div style="font-size:38px">▣</div><h3>Scan identity document</h3><p class="muted">Camera/reader integration would replace this simulated input in production.</p><div class="search"><input id="q2" placeholder="ID, passport, birth record or VeriNam ID"><button class="primary" onclick="lookup(\'q2\')">Scan / Search</button></div></div></div>'}
function lookup(id){var q=(document.getElementById(id).value||"").trim(),p=patients[q],ks=Object.keys(patients),i;if(!p){for(i=0;i<ks.length;i++)if(patients[ks[i]].vn===q){p=patients[ks[i]];break}}if(!p){S.unknown=q;A("No patient match for "+q,"NOT FOUND");S.page="register";render();return}S.patient=p;S.encounter=false;S.emergency=false;S.tab="summary";A("Identified "+p.vn);S.page="patient";render()}
function register(){if(!R().register)return '<h1 class="title">First-time Registration</h1><div class="restricted">This role cannot create patient identities.</div>';return '<h1 class="title">First-time Registration</h1><p class="subtitle">Reuse verified identity information and collect only what is missing.</p>'+(S.unknown?'<div class="alert">No existing record found for <b>'+E(S.unknown)+'</b>.</div>':'')+'<div class="card" style="margin-top:16px"><div class="formgrid">'+fld("nid","Document / temporary identifier",S.unknown)+sel("nit","Identity type",["Namibian ID","Passport","Birth record","Residence document","Temporary / no document"])+fld("nn","Full legal name","")+fld("nd","Date of birth","")+sel("ns","Sex",["Female","Male","Other / not recorded"])+fld("nat","Nationality","Namibian")+fld("np","Phone","")+fld("nt","Town / address","")+sel("nc","Healthcare funding",["State patient","No insurance / public patient","PSEMAS","Private medical aid","Self-pay","Foreign/travel insurance","Unknown"])+fld("nprov","Provider / scheme","")+'</div><div class="actions"><button class="primary" onclick="create()">Create VeriNam profile</button><button class="secondary" onclick="go(\'find\')">Cancel</button></div></div>'}
function fld(id,l,v){return '<div class="field"><label>'+E(l)+'</label><input id="'+id+'" value="'+E(v||"")+'"></div>'}function sel(id,l,a){var s='<div class="field"><label>'+E(l)+'</label><select id="'+id+'">';for(var i=0;i<a.length;i++)s+='<option>'+E(a[i])+'</option>';return s+'</select></div>'}
function create(){var id=document.getElementById("nid").value.trim()||("TMP-"+Date.now()),p={vn:"VN-"+Math.floor(10000000+Math.random()*89999999),id:id,idtype:document.getElementById("nit").value,name:document.getElementById("nn").value||"Unnamed patient",dob:document.getElementById("nd").value||"Unknown",sex:document.getElementById("ns").value,nationality:document.getElementById("nat").value||"Unknown",status:"Pending verification",phone:document.getElementById("np").value||"Not provided",town:document.getElementById("nt").value||"Not provided",emergency:"Not provided",coverage:{type:document.getElementById("nc").value,provider:document.getElementById("nprov").value||"Not recorded",status:"Recorded"},allergies:[],conditions:[],meds:[],encounters:[],labs:[],referrals:[],children:[]};patients[id]=p;S.patient=p;S.unknown="";S.page="patient";A("Created "+p.vn);render()}
function patient(){var p=S.patient;if(!p)return '<div class="alert">No patient selected.</div>';return '<div class="patient-head"><div><h1 class="title">'+E(p.name)+'</h1><p class="subtitle">'+E(p.vn)+' · '+E(p.idtype)+' '+E(p.id)+' · '+E(p.dob)+' · '+E(p.nationality)+'</p></div><span class="badge '+(p.status.toLowerCase().indexOf("verified")>=0?"ok":"warn")+'">'+E(p.status)+'</span></div>'+(S.emergency?'<div class="banner emergency-banner"><b>Emergency break-glass access active.</b> This event is specially logged for review.</div>':S.encounter?'<div class="success">Active encounter at '+E(S.user.facility)+'.</div>':'<div class="alert">No active encounter. Clinical information remains restricted.</div>')+'<div class="tabs">'+tab("summary","Summary")+tab("journey","Patient Journey")+tab("children","Children / Guardian")+tab("coverage","Coverage")+'</div>'+ptab(p)}
function tab(x,t){return '<button class="'+(S.tab===x?"active":"")+'" onclick="S.tab=\''+x+'\';render()">'+t+'</button>'}
function ptab(p){if(S.tab==="journey")return journey(p);if(S.tab==="children")return children(p);if(S.tab==="coverage")return coverage(p);return summary(p)}
function allowed(){return R().clinical&&(S.encounter||S.emergency)}
function summary(p){var ok=allowed(),s='<div class="grid g2"><div class="card"><h3>Patient details</h3>'+info("Phone",p.phone)+info("Town / address",p.town)+info("Emergency contact",p.emergency);if(R().checkin&&!S.encounter&&!S.emergency)s+='<div class="actions"><button class="primary" onclick="S.encounter=true;A(\'Opened encounter for '+p.vn+'\');render()">Check in / open encounter</button></div>';if(S.encounter)s+='<button class="secondary" onclick="S.encounter=false;A(\'Closed encounter for '+p.vn+'\');render()">Close encounter</button>';s+='</div><div class="card"><h3>Emergency clinical summary</h3>';if(ok){A("Viewed clinical summary");s+=info("Allergies",p.allergies.join(", ")||"None recorded")+info("Conditions",p.conditions.join(", ")||"None recorded")+info("Current medication",p.meds.join(", ")||"None recorded")}else{s+='<div class="restricted">Requires an authorised clinical role plus active encounter or emergency access.</div>';if(!R().clinical)A("Attempted clinical access","DENIED")}return s+'</div></div><div class="grid g2" style="margin-top:17px"><div class="card"><h3>Active referrals</h3>'+refs(p)+'</div><div class="card"><h3>Recent laboratory results</h3>'+(ok?labs(p):'<div class="restricted">Clinical access required.</div>')+'</div></div>'}
function info(a,b){return '<div class="row"><div><div class="label">'+E(a)+'</div><div class="value">'+E(b)+'</div></div></div>'}
function refs(p){if(!p.referrals.length)return '<div class="muted">No active referrals.</div>';var s="";for(var i=0;i<p.referrals.length;i++)s+='<div class="row"><div><b>'+E(p.referrals[i][2])+'</b><div class="label">'+E(p.referrals[i][3])+' · from '+E(p.referrals[i][1])+'</div></div><span class="badge info">'+E(p.referrals[i][4])+'</span></div>';return s}
function labs(p){if(!p.labs.length)return '<div class="muted">No recent results.</div>';var s="";for(var i=0;i<p.labs.length;i++)s+='<div class="row"><div><b>'+E(p.labs[i][1])+'</b><div class="label">'+E(p.labs[i][0])+' · '+E(p.labs[i][2])+'</div></div><span class="badge ok">'+E(p.labs[i][3])+'</span></div>';return s}
function journey(p){var can=allowed(),s='<div class="card"><h3>National encounter timeline</h3><div class="timeline">';if(!p.encounters.length)s+='<div class="muted">No previous encounters.</div>';for(var i=0;i<p.encounters.length;i++)s+='<div class="event"><b>'+E(p.encounters[i][1])+'</b><small>'+E(p.encounters[i][0])+' · '+E(p.encounters[i][2])+'</small><div>'+E(p.encounters[i][3])+(can?' · <b>'+E(p.encounters[i][4])+'</b>':' · Diagnosis restricted')+'</div></div>';return s+'</div></div>'}
function children(p){var s='<div class="grid g2"><div class="card"><h3>Linked children / dependants</h3>';if(!p.children.length)s+='<div class="muted">No linked dependants.</div>';for(var i=0;i<p.children.length;i++){var c=patients[p.children[i]];s+='<div class="row"><div><b>'+E(c.name)+'</b><div class="label">'+E(c.dob)+' · '+E(c.idtype)+'</div></div><button class="secondary" onclick="openChild(\''+E(c.id)+'\')">Open</button></div>'}s+='</div><div class="card"><h3>Guardian relationship</h3>';s+=p.guardian?info("Guardian",p.guardian.name)+info("Relationship",p.guardian.relationship)+info("VeriNam ID",p.guardian.vn):'<div class="muted">No guardian recorded.</div>';return s+'</div></div>'}
function openChild(id){S.patient=patients[id];S.encounter=false;S.emergency=false;S.tab="summary";A("Opened linked child "+S.patient.vn);render()}
function coverage(p){return '<div class="card"><h3>Healthcare funding</h3>'+(R().coverage?info("Funding type",p.coverage.type)+info("Provider",p.coverage.provider)+info("Status",p.coverage.status):'<div class="restricted">Detailed funding information is restricted for this role.</div>')+'</div>'}
function emergency(){return '<h1 class="title">Emergency / Unidentified Patient</h1><p class="subtitle">Care must continue even when normal identification or consent is unavailable.</p><div class="grid g2"><div class="card"><h3>Known patient emergency access</h3><p class="muted">Enter an identifier and record a reason for break-glass access.</p>'+fld("eq","Patient identifier","90051400123")+'<div class="field"><label>Emergency reason</label><select id="er"><option>Patient unconscious / incapacitated</option><option>Immediate threat to life</option><option>Other emergency</option></select></div><button class="emergency" onclick="breakglass()">Request emergency access</button></div><div class="card"><h3>Unidentified patient</h3><p class="muted">Create a temporary identity so treatment can begin immediately. It can later be reconciled with the confirmed person.</p><button class="primary" onclick="tempPatient()">Create temporary emergency patient</button></div></div>'}
function breakglass(){var q=document.getElementById("eq").value.trim(),p=patients[q];if(!p){alert("No matching demo patient.");return}if(!R().clinical){A("Emergency access attempt for "+p.vn,"DENIED");alert("Emergency clinical access requires a clinical role.");return}S.patient=p;S.emergency=true;S.encounter=false;S.tab="summary";A("BREAK GLASS: "+document.getElementById("er").value+" for "+p.vn,"GRANTED");S.page="patient";render()}
function tempPatient(){var id="TMP-"+Date.now(),p={vn:"VN-"+Math.floor(10000000+Math.random()*89999999),id:id,idtype:"Temporary emergency identity",name:"Unknown patient",dob:"Unknown",sex:"Not recorded",nationality:"Unknown",status:"Unverified temporary identity",phone:"Unknown",town:"Unknown",emergency:"Unknown",coverage:{type:"Unknown",provider:"Unknown",status:"Pending"},allergies:[],conditions:[],meds:[],encounters:[],labs:[],referrals:[],children:[]};patients[id]=p;S.patient=p;S.emergency=R().clinical;S.encounter=false;S.tab="summary";A("Created temporary emergency patient "+p.vn);S.page="patient";render()}
function audit(){var s='<h1 class="title">Audit Log</h1><p class="subtitle">Successful, denied and emergency access events are traceable.</p><div class="card"><div class="tablewrap"><table><tr><th>Time</th><th>User</th><th>Role</th><th>Facility</th><th>Action</th><th>Result</th></tr>';for(var i=0;i<S.audit.length;i++)s+='<tr><td>'+E(S.audit[i][0])+'</td><td>'+E(S.audit[i][1])+'</td><td>'+E(S.audit[i][2])+'</td><td>'+E(S.audit[i][3])+'</td><td>'+E(S.audit[i][4])+'</td><td><span class="badge '+(S.audit[i][5]==="GRANTED"?"ok":S.audit[i][5]==="DENIED"?"bad":"warn")+'">'+E(S.audit[i][5])+'</span></td></tr>';return s+'</table></div></div>'}
render();
